### ISSUE TITLE
Is it possible to outsource the linear part to CPU instead of GPU?

### ISSUE THREAD

**Issue by ChengFu0118** [ftramer/slalom#11]
Dear Author,

I don't have a GPU for my PC, so I am wondering is there any settings for me to switch the outsource platform from untrusted GPU to CPU?

Thanks,
Cheng Fu

**Comment by ftramer** [comment]
In principle if you have a CPU at hand that's much faster that the fastest CPU with SGX (e.g., a highly multi-core server CPU), then outsourcing from SGX to the CPU would make sense!
I haven't tested this but I think it might be as simple as changing the "device" to cpu here:
https://github.com/ftramer/slalom/blob/master/python/slalom/scripts/eval.py#L58

**Comment by PegX** [comment]
Hello, i wanna ask how to solve "__builtin_shufflevector" problem during the compiling. I encountered this issue during the make.
Is it possible from different compiler?
