### ISSUE TITLE
Question about porting Eigen to enclave

### ISSUE THREAD

**Issue by Vampsj** [ftramer/slalom#13]
Hi, thank you for your wonderful work! I am trying to port the Eigen library into the enclave however even I add the Eigen path to the enclave's include path, I failed when I include Eigen/Dense in the enclave. 

There shows a lot of errors causing by sgxsdk/include/stlport/stl/SOMETHING.h

In my MAKEFILE, my Enclave_include_paths is as follows:
> Enclave_Include_Paths := -IEnclave -I$(SGX_SDK)/include -I$(SGX_SDK)/include/tl\
ibc -I$(SGX_SDK)/include/stlport -I$(SGX_SDK)/include/libcxx -I$(SGX_SDK)/inclu\
de/eigen3_sgx -I/usr/lib/gcc/x86_64-linux-gnu/5.4.0/include

And I add the 
> #include <Eigen/Dense>
in the enclave.cpp file.
Am I missing something or repeatedly included some libraries?

It would be very appreciated if someone can give me any suggestions, thank you.

**Comment by ftramer** [comment]
This seems unrelated to eigen and an issue with the core SGX sdk. Can you compile a simple sgx application that does not use eigen?

**Comment by Vampsj** [comment]
@ftramer Thank you so much for your reply. Yes, it is not the problem of eigen and the problem went away when I comment out this  
> -I$(SGX_SDK)/include/stlport
But still, thank you for your reply
