### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mhsamavatian** [ftramer/slalom#14]
I get this error when compile sgxDNN
/usr/lib/gcc/x86_64-linux-gnu/5/include/fmaintrin.h: In function ‘__m256d double_dot_prod_fmadd(__m256d, __m256d, __m256d, __m256d, __m256d)’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/fmaintrin.h:47:1: error: inlining failed in call to always_inline ‘__m256d _mm256_fmadd_pd(__m256d, __m256d, __m256d)’: target specific option mismatch
 _mm256_fmadd_pd (__m256d __A, __m256d __B, __m256d __C)
 ^
In file included from sgxdnn_main.cpp:12:0:
sgxdnn_main.hpp:114:37: error: called from here
  return _mm256_fmadd_pd(a1, b1, accu);

**Comment by ftramer** [comment]
This looks like your default compiler doesn't support AVX instructions. You might need to an '-mavx' flag somewhere.

**Comment by mhsamavatian** [comment]
Thanks for the guidance. 
the complete solution is you have to add the flags -mavx and -mfma in both Makefiles in SGXDNN and slalom directory.
