### ISSUE TITLE
The resnet2.py is missed.

### ISSUE THREAD

**Issue by mhsamavatian** [ftramer/slalom#15]
from python.slalom.models import get_model
  File "python/slalom/models.py", line 7, in <module>
    from python.slalom.resnet2 import ResNet34 as ResNet2_34, ResNet50 as ResNet2_50, ResNet101 as ResNet2_101, \
ImportError: No module named resnet2

**Comment by ftramer** [comment]
This seems to be a leftover import from a file that's no longer used. Sorry about that, you can safely remove that line.
