### ISSUE TITLE
Why ActivationQ doesn't support Sigmoid function?

### ISSUE THREAD

**Issue by gutouyu** [ftramer/slalom#16]
Could not understand why `ActivationQ` doesn't support `Sigmoid` function.

https://github.com/ftramer/slalom/blob/1badff914657398733b4136325066cf7c2f66168/python/slalom/quant_layers.py#L67

 What if I want to use `sigmoid` ?

Still try to understand this awesome work, Thanks.

**Comment by ftramer** [comment]
I didn't implement sigmoid as all the neural networks I evaluated used some variant of ReLUs.
It shouldn't be hard to add support for sigmoids though.
