### ISSUE TITLE
What's the meaning of running param "--no_slalom"？

### ISSUE THREAD

**Issue by gutouyu** [ftramer/slalom#17]
# File `run.sh`
I think the following code will run slalom with full power: integrity, privacy, quantize, batch verification, as well as preprocess. Am I right?

https://github.com/ftramer/slalom/blob/1badff914657398733b4136325066cf7c2f66168/run_all.sh#L48-L53

But I couldn't understand what's the meaning of params `--no_slalom`. The code says it is for 
>  help='only test GPU quantization')

 It is `False` by default.  I'm getting confused about this.  What's the meaning of `only test GPU quantization`?   Is it only a param for the test, so we don't need to pay attention to it? right? 

# class `ActivationQ`

https://github.com/ftramer/slalom/blob/1badff914657398733b4136325066cf7c2f66168/python/slalom/quant_layers.py#L81-L102

`slalom` is `True` and `quantize` is `True`,  so it seems like we actually do quantize in running time. (line )  Am I missing something?

Looking forward to hearing from you. Thanks a lot.

**Comment by ftramer** [comment]
Yes, the --no_slalom flag is just something I used in some internal tests to check how much the quantization itself slows down the inference. You shouldn't have to set that flag.
