### ISSUE TITLE
Integrity and Privacy guarantee question

### ISSUE THREAD

**Issue by gutouyu** [ftramer/slalom#18]
# Description
In readme.md, it said if we use `--blinding` and `--integrity` together, we will guarante privacy and verify computing integrity.  
```shell
python -m python.slalom.scripts.eval_slalom [vgg_16 | mobilenet | mobilenet_sep] --batch_size=8 --max_num_batches=4 {--blinding}  {--integrity} {--use_sgx}
```
# Question
When I look into the code, I find the blinded operations. But I just couldn't find something like `lib.predict_and_verify` for integrity check. The code just use `tensorflow` to get the `preds` and record the top-k acc. Apparently, in this way, we wouldn't check for integrity.
```python
preds = sess.run(model.outputs[0], feed_dict={model.inputs[0]: images,
                             backend.learning_phase(): 0},
                             options=run_options, run_metadata=run_metadata)
```

 So, where is the integrity check in this situation, am I missing something important?

# More
A little confused about this, try to run the code with both blinding and integrity, using CPU and GPU. As far as I know, 
- script `eval.py` only run for integrity (with batch_verification and preprocesse). 
- And  script `eval_slalom.py` only run for privacy, although readme says it will check for integrity and actually I don't think it will do that for now. 

Am I right about this? What do I need to do for getting both privacy and integrity guarantee?
Looking forward to hearing from you. Really need a little help. Thanks very much.

**Comment by ftramer** [comment]
So eval.py is only for integrity, that's correct. But eval_slalom.py can do both integrity and privacy. When running the predictions with tensorflow, the matrix multiplication operations are performed on the GPU and the activations are performed in a trusted enclave. The enclave takes care of blinding inputs to preserve privacy, and it also runs integrity checks at the same time.

**Comment by ftramer** [comment]
If we only need to do integrity checks, then we can simply run the whole model on the GPU, and then send all the intermediate results to the enclave to perform the checks (that's what eval.py does).

However, if we also want privacy, we have to switch between GPU and the enclave at every linear layer (so that the enclave can unblind the data, compute the non-linearity, and reblind).
To do this, we replace the activation layers in our models by a special ActivationQ layer. When this layer is called by TensorFlow, it actually sends the data to the enclave, waits for the response, and then proceeds with the evaluation on the GPU.
(see https://github.com/ftramer/slalom/blob/master/python/slalom/quant_layers.py#L90).

So in the end, we can just call sess.run() and TensorFlow takes care of running the layers in the right order. Every time it hits an ActivationQ layer, it communicates with the enclave.
Does that make sense?

**Comment by gutouyu** [comment]
Thanks, that really helped a lot. Absolutely, what you said is very reasonable. I didn't pay much attention to this line in `ActivationQ` before, and missing so important line, so sad:
> outputs = self.sgxutils.relu_slalom(inputs, blind, activation=self.activation)

So, 
## Q1
- This the `relu` in `sgxutils.relu_slalom` just stands for `activation`, right? If we use any other activation, it would always be this function  called. I think `relu` may couse some confusion.

## Q2
>However, if we also want privacy, we have to switch between GPU and the enclave at every linear layer (so that the enclave can unblind the data, compute the non-linearity, and reblind).

- In my understanding,  if we use privacy and integrity together, then the whole process would be : 
the enclave unblind the data ->  **integrity check** ->  **add bias**  -> compute the non-linearity ->  reblind -> send back to GPU   
Is that right?

Still be confused about the detailed and  accurate process about ` integrity check` and `bias-add ` when we use **privacy + integrity**.
## Q3
The GPU only compute for `F(x, W)` which `F` stands only for matrix-product, it doesn't include the `BiasAdd, Activation`.  So the `Activation, BiasAdd` all do in the tee enclave.Am I right about this? 

Thanks again for your reply, really give me a lot of help.

**Comment by ftramer** [comment]
Q1: For now, only ReLU is implemented on the enclave side so I just called this relu everywhere.

Q2: Yes, that's right (except that the bias is added by the GPU). Think of it this way: 
- the enclave has some input X. It blinds it into X'=X+R and sends that to the GPU. 
- The GPU computes Z'=W*X' + b and sends Z' back to the enclave.
- The enclave computes Z' - W*R = W*X + b to unblind the results (where W*R was precomputed).
- The enclave applies Freivalds' to check that W*(X*r) + (b*r) = (W*X+b)*r. This is the integrity check. Note that b*r can be precomputed so including the bias in the check is pretty much for free.
- The enclave computes X = ReLU(W*X + b), blinds X, and sends it to the GPU, etc.

Q3: As explained above, the GPU does compute the bias addition, but it does not compute the activation.

**Comment by gutouyu** [comment]
So clear! Thanks very much.
