### ISSUE TITLE
Freivald check for Dense and Conv Layer questions

### ISSUE THREAD

**Issue by gutouyu** [ftramer/slalom#20]
# Freivald's check doesn't directly apply to fully-connected DNN 
In the paper **section 3.2**,  part: **Applying Freivald's algorithm**  says:
> Similarly, Freivald's check doesn't directly apply to fully connected layers, as they compute a *vector-matrix* product. We thus consider further techniques, ...

## Q1
In this situation, only when `batch_size=1`, the fully-connected DNN will be *vector-matrix* product, because the input `x` is just a vector.  But when `batch_size > 1`, even fully-connected DNN will be *matrix-matrix* product, and we can use Freivald's algorithm in this way. 
Am I understanding it right?

# For convolutions, we apply Freivald's check twice
Also in paper **section 3.2**, part: **Batching verifications.** says:
> For convolutions, we apply Freivald's check twice, to also reduce the cost of computing F(rX).  ....  `Conv(r1X, W r2) = r1 Z r2`...

## Q2
- Using Freivald's check twice means there will be `r1 r2` and `r1'  r2'` , 4 random vectors in total. Am I right?
- What's `F` stands for? the matrix-product? Is the AddBias included? And is the Activation included? How could this will **reduce the cost of computing F(rx)**? 
- In part **Applying Freivald's algorithm** part, it says we can directly apply Freivald's check for convolution using a `r` of size `c_out`: `Conv(x, Wr) = Zr`.  But the above part says we need `r1, r2` and use Freivald's check twice. What's the difference? Totally confused.

Please forgive me for so many questions. I think you've done an outstanding job, but for these details, I just have trouble understanding it.

**Comment by ftramer** [comment]
For Q1, yes if you have a batch of size N you get a matrix multiplication X*W where X has dimension (N x h_in) and W has dimension (h_in x h_out). So with Freivald's check, you save a factor N (or h_out, which ever is smaller).

For Q2, F(X) is the convolution operator, without the bias or activation. There's multiple ways to apply Freivald's algorithm for convolutions. One easy way is to check that Conv(X, W*r) = Z*r. If X is a batch of size N, we can save even more by doing a check of the form Conv(r1*X, W*r2) = r1*Z*r2 instead, for two random vectors r_1, r_2. In practice, we can choose which option to use.

**Comment by gutouyu** [comment]
Thanks, that's really help
