### ISSUE TITLE
Random r vector

### ISSUE THREAD

**Issue by mhsamavatian** [ftramer/slalom#22]
In for example conv2d.hpp file the random r vector generated like below:
   Tensor<double, 2> r(ch_out, REPS);
    r.setConstant(1 << 20);
isn't r suppossed to be random? 
isn't r supposed to be vector of 0 and 1 values? why 1<<20
Where is the factor K to redo the verification k times?

**Comment by ftramer** [comment]
Yes, for some of the experiments I got a bit lazy and didn't actually generate the vectors randomly but as a constant vector. This is just a research prototype, and the performance cost of generating the random values is negligible so I just did without.
The number of repetition is configured by the REPS constant you see in the code fragment. 
To get 40 bits of soundness with Freivalds' check, you can pick r with values in {0,1} and repeat 20 times, or you could pick r with values in {-2^20, 2^20} and repeat twice. The latter is much more efficient and that's what we do.

Sorry about the confusion with this. These details should have been better documented in the code.

**Comment by mhsamavatian** [comment]
Why 20? do you mean 40? 
|S| = 2^20, k=2
|S| = 2 {0,1} so k=40
Am I wronge?

**Comment by ftramer** [comment]
Yes, that's right thanks
