### ISSUE TITLE
loop over output_map

### ISSUE THREAD

**Issue by mhsamavatian** [ftramer/slalom#23]
in the following loop in conv2d layer:
for (int i=0; i<h\*w; i++) {
for(int j=0; j<ch_out; j++) {
for(int r=0; r<REPS; r++) {
out1.data()[r\*ch_out + j] -= static_cast<double>(output_map.data()[i\*ch_out + j]) \* r_left.data()[r\*h\*w + i];
	}
     }
}
how the loop is over h\*w since for some layers the output height and width are different, declared as h_out and w_out.

**Comment by mhsamavatian** [comment]
I think there is a bug within this line
} else if (kernel_.dimension(0) == 1 && kernel_.dimension(0) == 1) 
first  I think the second condition should be  kernel_.dimension(1) == 1 
second this should grantee that input and output h and w be equal but there are some cases of convolution with different input output size that get into this 'if' condition.
When I check eq for these cases it is: "eq: 0" meaning that integrity check failed. 
I do not know how when filter size is 1x1 input-output size are not equal if this is the meaning of the condition.

**Comment by ftramer** [comment]
This is for pointwise convolutions where the kernel is of size 1x1. You're right that there seems to be a typo in the check.
I only ever checked convolutions where the kernel is squared, so there might be some hidden bugs for the general case. In particular, you're right that if the kernel is of size 1xk something probably breaks. But these kernels are never used in practice as far as I know.

**Comment by mhsamavatian** [comment]
Yes, that's right. I corrected the condition kernel_.dimension(0) == 1 && kernel_.dimension(1) ==1 to make sure it gets into the if when the kernel is 1x1 but when I run it with resnet50 and kernel size is 1x1 I print the h,w h_out, and w_out and they are not identical and as I said eq is also 0. So there is another problem here besides 1xk kernel size.

**Comment by ftramer** [comment]
Maybe your convolution is using strides larger than 1. I think I only thought about the stride=1 case when implementing this, and it that case you would have h=h_out and w=w_out.

**Comment by mhsamavatian** [comment]
yes, it can be that.  I will check, thanks.

**Comment by mhsamavatian** [comment]
I checked It is the stride issue. In this case, should it be redirected to the next condition block that using convolution with im2col?
