### ISSUE TITLE
About Imagenet dataset

### ISSUE THREAD

**Issue by ohsai** [ftramer/slalom#28]
I am currently trying ```eval.py``` to test the code, but it requires the imagenet validation dataset. So I am trying to download it from tensorflow git repo ```tensorflow/models``` by executing shell scripts on ```research/inception/inception/data/download_imagenet.sh```. The question is : 

1. Do we need the entire imagenet validation dataset? dataset seemed pretty large.. 

2. Do we need to preprocess the dataset after downloading and unzipping it, or do we simply need to place it in ```../imagenet``` directory? If preprocessing is needed, how can I do it?

3. Do we need to convert the dataset to TFRecord? If it is necessary, how can I do it? (after downloading ```ILSVRC2012_img_val.tar``` from imagenet website)

**Comment by ftramer** [comment]
1) You only need the validation set (or a subset of it) to evaluate
2-3) I followed the instructions here: https://github.com/tensorflow/models/tree/master/research/slim#Data

This was a while ago though, and I remember it not being a super easy process. At the end of it, you should have the ImageNet dataset in TFRecord format. The images are automatically preprocessed before being input to the model.

**Comment by DRyan1995** [comment]
@ohsai I'm having the exact same issue right now to get the dataset ready, did you have any luck on this? It would be greatly appreciated if any help can provided!

**Comment by bronzeMe** [comment]
@ohsai @ftramer @DRyan1995 Hi, when I run "python -m python.slalom.scripts.eval mobilenet sgxdnn --batch_size=8 --max_num_batches=4 --verify  --verify_batched --use_sgx",  it returned an error "ValueError: No data files found in ../imagenet/validation-*".
I think the error is same as this issue, but I am a beginner for tensorflow,  could you give some detial tips about downloading the  validation dataset, please? Thanks.

**Comment by GuoJinnan** [comment]
@bronzeMe same issue. Have u tackle this issue now?

**Comment by GuoJinnan** [comment]
Hi guys:

Convert the input data to tfrecord format first. Then rename the generated tf-record validation file to validation-xxxxx-of-xxxxx.tfrecord will help.

**Comment by bronzeMe** [comment]
@GuoJinnan Thank you so much !! I will try it.
