### ISSUE TITLE
vgg16.json can't be found

### ISSUE THREAD

**Issue by gutouyu** [ftramer/slalom#4]
In file `enclave_bridge.cpp` we first load vgg16 to model as below:
```c++
std::ifstream t("App/vgg16.json");
std::stringstream buffer;
buffer << t.rdbuf();
std::cout << buffer.str() << std::endl;
```
but I couldn't find `App/vgg16.json` file in the repo, Am I supposed to download it myself? If so, where could I download it. As the model is load nothing, I can not run `./slalom_app` without errors.

Looking forward to hear from you, really need ur help. Thank you.

**Comment by ftramer** [comment]
The main function in `enclave_bridge.cpp` is just used for internal testing purposes. Sorry for the confusion. We call Slalom through a python interface, as explained in the README. This generates a json representation of the input model, which is then passed to the SGX enclave (but never written out to disk).

**Comment by gutouyu** [comment]
Thank you very much.  Got it.
