### ISSUE TITLE
I cannot run this project.

### ISSUE THREAD

**Issue by Karssadin** [ftramer/slalom#53]
I have installed the sgxsdk successful.

I clone the slalom code : `git clone https://github.com/ftramer/slalom.git`

I create a envs : `sudo conda create -n tf1_8 python=2.7`

then i run the command 
```
conda activate tf1_8 
pip install tensorflow-gpu==1.8
cd slalom
pip install -r requirements.txt
```

the `pip list` output:
```
(tf1_8) ksd@ksd:~/slalom/Include$ pip list
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Package              Version
-------------------- -----------
absl-py              0.2.2
astor                0.6.2
backports.csv        1.0.7
backports.weakref    1.0.post1
bleach               3.1.4
certifi              2021.10.8
chardet              4.0.0
defusedxml           0.7.1
diff-match-patch     20200713
Django               1.11.29
django-import-export 1.2.0
enum34               1.1.10
et-xmlfile           1.0.1
funcsigs             1.0.2
futures              3.3.0
gast                 0.2.0
grpcio               1.12.1
h5py                 2.8.0
html5lib             0.9999999
idna                 2.10
jdcal                1.4.1
Keras                2.1.5
Keras-Applications   1.0.5
Keras-Preprocessing  1.0.3
Markdown             2.6.11
MarkupPy             1.14
mock                 3.0.5
numpy                1.14.4
odfpy                1.4.1
opencv-python        4.2.0.32
openpyxl             2.6.4
pip                  20.3.4
protobuf             3.5.2.post1
pytz                 2022.1
PyYAML               5.1
requests             2.27.1
scipy                1.1.0
setuptools           44.1.1
six                  1.11.0
tablib               0.14.0
tensorboard          1.8.0
tensorflow           1.8.0
tensorflow-gpu       1.8.0
termcolor            1.1.0
urllib3              1.26.9
webencodings         0.5.1
Werkzeug             0.15.3
wheel                0.37.1
xlrd                 2.0.1
xlwt                 1.3.0
```

then i run the command:
```
cd slalom/App
make
make -f Makefile_cu
```
It was okay.

then i run the command:
```
cd slalom/SGXDNN
make
```
there is an bug: 
```
Assembler messages:
致命错误： can't create bin/sgxdnn_main.o: 没有那个文件或目录
Makefile:26: recipe for target 'bin/sgxdnn_main.o' failed
make: *** [bin/sgxdnn_main.o] Error 1
```
I have copy the eigen to include with whe command:` sp /usr/local/include/eigen3/* -r /home/ksd/slalom/Include/eigen`

how to fix it?

**Comment by Karssadin** [comment]
this bug has been fixed with the proposal in [there](https://github.com/ftramer/slalom/issues/27).
but i meet another bug when i run the command:
```
cd slalom
make
```
the bug log is:
```
In file included from Enclave/sgxdnn.cpp:3:0:
SGXDNN/sgxdnn_main.hpp:4:10: fatal error: immintrin.h: No such file or directory
 #include <immintrin.h>
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:228: recipe for target 'Enclave/sgxdnn.o' failed
make: *** [Enclave/sgxdnn.o] Error 1

```

**Comment by Karssadin** [comment]
this bug has been fixed after i "export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/lib/gcc/x86_64-linux-gnu/7/include"
but when i built all file,i run the `./run_all.sh`
there is an another bug in `results/benchmarks.txt`:
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/ksd/anaconda3/envs/tf1_8/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ksd/anaconda3/envs/tf1_8/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ksd/slalom/python/slalom/scripts/benchmarks.py", line 7, in <module>
    from python.slalom.sgxdnn import SGXDNNUtils
  File "python/slalom/sgxdnn.py", line 11, in <module>
    from python.slalom.quant_layers import Conv2DQ, DenseQ, DepthwiseConv2DQ, ActivationQ
  File "python/slalom/quant_layers.py", line 20, in <module>
    fmod_module = tf.load_op_library('./App/cuda_fmod.so')
  File "/home/ksd/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./App/cuda_fmod.so: undefined symbol: __cudaPushCallConfiguration
```

**Comment by ftramer** [comment]
I haven't encountered this error before.
Some googling suggests that it could be due to an incompatibility between your CUDA and tensorflow versions.

**Comment by Karssadin** [comment]
> I haven't encountered this error before. Some googling suggests that it could be due to an incompatibility between your CUDA and tensorflow versions.


I install the tensorflow with the command `pip install tensorflow-gpu==1.8` and the in the official [link](https://www.tensorflow.org/install/source#linux) ,the cuda of 1.8 version tensorflow is 9.0

the command `nvcc -V` output:
```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```
The version seems to be correct

**Comment by Arrowflyt** [comment]
> > I haven't encountered this error before. Some googling suggests that it could be due to an incompatibility between your CUDA and tensorflow versions.
> 
> I install the tensorflow with the command `pip install tensorflow-gpu==1.8` and the in the official [link](https://www.tensorflow.org/install/source#linux) ,the cuda of 1.8 version tensorflow is 9.0
> 
> the command `nvcc -V` output:
> 
> ```
> nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2017 NVIDIA Corporation
> Built on Fri_Sep__1_21:08:03_CDT_2017
> Cuda compilation tools, release 9.0, V9.0.176
> ```
> 
> The version seems to be correct



> this bug has been fixed after i "export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/lib/gcc/x86_64-linux-gnu/7/include" but when i built all file,i run the `./run_all.sh` there is an another bug in `results/benchmarks.txt`:
> 
> ```
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "/home/ksd/anaconda3/envs/tf1_8/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/home/ksd/anaconda3/envs/tf1_8/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/home/ksd/slalom/python/slalom/scripts/benchmarks.py", line 7, in <module>
>     from python.slalom.sgxdnn import SGXDNNUtils
>   File "python/slalom/sgxdnn.py", line 11, in <module>
>     from python.slalom.quant_layers import Conv2DQ, DenseQ, DepthwiseConv2DQ, ActivationQ
>   File "python/slalom/quant_layers.py", line 20, in <module>
>     fmod_module = tf.load_op_library('./App/cuda_fmod.so')
>   File "/home/ksd/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
>     lib_handle = py_tf.TF_LoadLibrary(library_filename)
> tensorflow.python.framework.errors_impl.NotFoundError: ./App/cuda_fmod.so: undefined symbol: __cudaPushCallConfiguration
> ```

Hi Pureloverdi, When I run the code, I also met this problem, my cuda version is 10.1, have you sloved this problem finally?

**Comment by Peter1101Zhang** [comment]
> > I haven't encountered this error before. Some googling suggests that it could be due to an incompatibility between your CUDA and tensorflow versions.
> 
> I install the tensorflow with the command `pip install tensorflow-gpu==1.8` and the in the official [link](https://www.tensorflow.org/install/source#linux) ,the cuda of 1.8 version tensorflow is 9.0
> 
> the command `nvcc -V` output:
> 
> ```
> nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2017 NVIDIA Corporation
> Built on Fri_Sep__1_21:08:03_CDT_2017
> Cuda compilation tools, release 9.0, V9.0.176
> ```
> 
> The version seems to be correct

Hi Karssadin, I also encountered this problem,my cuda version is also 9.0.Could you tell me how you finally solved this problem?Really appreciate it !

**Comment by Peter1101Zhang** [comment]
> > > I haven't encountered this error before. Some googling suggests that it could be due to an incompatibility between your CUDA and tensorflow versions.
> > 
> > 
> > I install the tensorflow with the command `pip install tensorflow-gpu==1.8` and the in the official [link](https://www.tensorflow.org/install/source#linux) ,the cuda of 1.8 version tensorflow is 9.0
> > the command `nvcc -V` output:
> > ```
> > nvcc -V
> > nvcc: NVIDIA (R) Cuda compiler driver
> > Copyright (c) 2005-2017 NVIDIA Corporation
> > Built on Fri_Sep__1_21:08:03_CDT_2017
> > Cuda compilation tools, release 9.0, V9.0.176
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The version seems to be correct
> 
> > this bug has been fixed after i "export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/lib/gcc/x86_64-linux-gnu/7/include" but when i built all file,i run the `./run_all.sh` there is an another bug in `results/benchmarks.txt`:
> > ```
> > Using TensorFlow backend.
> > Traceback (most recent call last):
> >   File "/home/ksd/anaconda3/envs/tf1_8/lib/python2.7/runpy.py", line 174, in _run_module_as_main
> >     "__main__", fname, loader, pkg_name)
> >   File "/home/ksd/anaconda3/envs/tf1_8/lib/python2.7/runpy.py", line 72, in _run_code
> >     exec code in run_globals
> >   File "/home/ksd/slalom/python/slalom/scripts/benchmarks.py", line 7, in <module>
> >     from python.slalom.sgxdnn import SGXDNNUtils
> >   File "python/slalom/sgxdnn.py", line 11, in <module>
> >     from python.slalom.quant_layers import Conv2DQ, DenseQ, DepthwiseConv2DQ, ActivationQ
> >   File "python/slalom/quant_layers.py", line 20, in <module>
> >     fmod_module = tf.load_op_library('./App/cuda_fmod.so')
> >   File "/home/ksd/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
> >     lib_handle = py_tf.TF_LoadLibrary(library_filename)
> > tensorflow.python.framework.errors_impl.NotFoundError: ./App/cuda_fmod.so: undefined symbol: __cudaPushCallConfiguration
> > ```
> 
> Hi Pureloverdi, When I run the code, I also met this problem, my cuda version is 10.1, have you sloved this problem finally?

Hi Arrowflyt, I also encountered this problem,my cuda version is also 9.0.Could you tell me how you finally solved this problem?Really appreciate it !
