### ISSUE TITLE
dense.hpp don't find the verification of XW=Z

### ISSUE THREAD

**Issue by gutouyu** [ftramer/slalom#6]
In `layer.hpp` you define a Interface Layer, which has two interfaces:
```c++
 TensorMap<T, 4> apply(TensorMap<T, 4> input_map, void* device_ptr = NULL)  {
        auto result = apply_impl(input_map, device_ptr);
        return result;
  }

 TensorMap<T, 4> fwd_verify(TensorMap<T, 4> input_map, float* extra_data, void* device_ptr = NULL)  {
        auto result = fwd_verify_impl(input_map, extra_data, device_ptr);
        return result;
 }
```

If I'm correct, `apply` will do the forward pass, and `fwd_verify` will do the forward_pass and verify the  results to check if it's calculated correctly. But when I see `dense.hpp`, I don't see the check (Freivald's Algorithm, `XW = Z`), here is the code:
```c++
TensorMap<T, 4> apply_impl(TensorMap<T, 4> input, void* device_ptr = NULL) override {
          ......
}


TensorMap<T, 4> fwd_verify_impl(TensorMap<T, 4> input, float* extra_data, void* device_ptr) {
	int batch;

	if (input.dimension(0) == 1 && input.dimension(1) == 1)
	{
		batch = input.dimension(2);
	}
	else
	{
		batch = input.dimension(0);
	}
	output_shape_[2] = batch;

	if (verif_preproc_) {
		assert(batch == 1);
	}
	return apply_impl(input, device_ptr);
}
```

In the `fwd_verify_impl func of dense Layer`, there is just some input value check.  Am'I missing something? Sorry for these questions, I'm woking on your projects with my graduate classmates, we really think your work is awesome. Looking forward to get your help. Thanks :)

**Comment by ftramer** [comment]
Good catch. A dense layer can actually ne viewed as a 1x1 convolution, so we replace all dense layers by convolution layers when doing verification. We did this mainly because we had already implemented everything for point wise convolutions and wanted to reuse that.
We should mark this more clearly.

**Comment by gutouyu** [comment]
Wow, Got it! Thanks a lot.
