### ISSUE TITLE
Question about running slalom app

### ISSUE THREAD

**Issue by jpyo0803** [ftramer/slalom#63]
Hi!

When I run the "run_all.sh" it keeps saying the error below

tensorflow.python.framework.errors_impl.NotFoundError: ../imagenet; No such file or directory

It seems like a file called "imagenet" should have been in the "python/slalom" directory

Could you please help me figure out what that file is?

Thanks in advance!

**Comment by ftramer** [comment]
That's the path to the imagenet dataset which you have to download first.

**Comment by jpyo0803** [comment]
Thanks for the response!

**Comment by jpyo0803** [comment]
I am sorry to ask you more questions but can I ask you what Imagenet data did you use exactly? 

What would be the data type (is it a bunch of raw image files)?

Thanks!

**Comment by jpyo0803** [comment]
Never mind! I figured it out.
