### ISSUE TITLE
Alternative choice for Interl_AES_GCM implementation

### ISSUE THREAD

**Issue by gutouyu** [ftramer/slalom#9]
Hi ftramer: @ftramer 

For efficient reason we use Inter_NI implementation of AES_GCM. I see we use it in the code `layers/dense.cpp layers/conv2d.cpp` etc.  

But what if I want to run the SGXDNN code in another platform such as ARM? We can not use the intel Inter_NI or the assembly code of course. Is there any convenient way to modify the code, so I can run it without the intel_aes_gcm?

I think of two ways to run the code:
1. Change the aes_gcm function implementation using c code(mbedtls library or kind of), instead of the origin intel_x86 assembly code. But as the signature of functions are not exactly the same, we still need some time to modify it.
2. Delete every code in the SGXDNN using the aes_gcm, as I believe in the paper, we actually didn't use it for privacy.  What's your opinion?

Do you have any suggestions about this? Any advice would be much appreciated.

**Comment by ftramer** [comment]
Porting the library to a non-intel architecture would require a significant amount of work for more reasons that just AES-NI. We also make use of a lot of other Intel SIMD instructions to speed-up operations so these would have to be converted to ARM as well.

**Comment by gutouyu** [comment]
Got it. Thanks a lot.
